#!/bin/bash
sudo pacman -S --noconfirm gum
confirm() {
  gum confirm \
    --selected.background "15" \
    --selected.foreground "0" \
    --unselected.foreground "8" \
    --prompt.foreground "15" \
    "$@"
}

confirm "install installer dependicies?" && sudo pacman -S gum git 
confirm "proceed with installation?" && sudo pacman -S --noconfirm sway waybar foot fuzzel ttf-jetbrains-mono-nerd && yay -S ttf-google-sans 
confirm "do you want to download and install config?" && git clone https://github.com/RedpPerson124/dotfiles
cp -r ~/dotfiles/config/sway ~/.config
cp -r ~/dotfiles/config/waybar ~/.config
cp -r ~/dotfiles/config/foot ~/.config
cp -r ~/dotfiles/config/fuzzel ~/.config 
